### ISSUE TITLE
Symfony v4 + flex: Attempted to call an undefined method "setContainer" of class "Doctrine\Bundle\DoctrineBundle\Registry"

### ISSUE THREAD

**Issue by diaboloshogunate** [doctrine/doctrine2#6784]
Getting an error when trying to install the orm

Here is the output when running composer require.

```text
composer require "doctrine/orm:^2.6-dev"
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 255
!!
!!  Fatal error: Uncaught Symfony\Component\Debug\Exception\UndefinedMethodException: Attempted to call an undefined method named "setContainer" of class "Doctrine\Bundle\DoctrineBundle\Registry". in C:\Users\rpark\Desktop\symfony-template\vendor\doctrine\doctrine-bundle\Registry.php:41
!!  Stack trace:
!!  #0 C:\Users\rpark\Desktop\symfony-template\var\cache\dev\ContainerNxmGNek\getDoctrineService.php(8): Doctrine\Bundle\DoctrineBundle\Registry->__construct(Object(ContainerNxmGNek), Array, Array, 'default', 'default')
!!  #1 C:\Users\rpark\Desktop\symfony-template\var\cache\dev\ContainerNxmGNek\Container.php(94): require('C:\\Users\\rpark\\...')
!!  #2 C:\Users\rpark\Desktop\symfony-template\var\cache\dev\ContainerNxmGNek\getCacheWarmerService.php(13): ContainerNxmGNek->load('C:\\Users\\rpark\\...')
!!  #3 C:\Users\rpark\Desktop\symfony-template\vendor\symfony\http-kernel\CacheWarmer\CacheWarmerAggregate.php(43): ContainerNxmGNek->{closure}()
!!  #4 C:\Users\rpark\Desktop\symfony-template\vendor\symfony\http-kernel\Kernel.php(511): Symfony\Componen in C:\Users\rpark\Desktop\symfony-template\vendor\doctrine\doctrine-bundle\Registry.php on line 41
!!
!!  PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\UndefinedMethodException: Attempted to call an undefined method named "setContainer" of class "Doctrine\Bundle\DoctrineBundle\Registry". in C:\Users\rpark\Desktop\symfony-template\vendor\doctrine\doctrine-bundle\Registry.php:41
!!  Stack trace:
!!  #0 C:\Users\rpark\Desktop\symfony-template\var\cache\dev\ContainerNxmGNek\getDoctrineService.php(8): Doctrine\Bundle\DoctrineBundle\Registry->__construct(Object(ContainerNxmGNek), Array, Array, 'default', 'default')
!!  #1 C:\Users\rpark\Desktop\symfony-template\var\cache\dev\ContainerNxmGNek\Container.php(94): require('C:\\Users\\rpark\\...')
!!  #2 C:\Users\rpark\Desktop\symfony-template\var\cache\dev\ContainerNxmGNek\getCacheWarmerService.php(13): ContainerNxmGNek->load('C:\\Users\\rpark\\...')
!!  #3 C:\Users\rpark\Desktop\symfony-template\vendor\symfony\http-kernel\CacheWarmer\CacheWarmerAggregate.php(43): ContainerNxmGNek->{closure}()
!!  #4 C:\Users\rpark\Desktop\symfony-template\vendor\symfony\http-kernel\Kernel.php(511): Symfony\Componen in C:\Users\rpark\Desktop\symfony-template\vendor\doctrine\doctrine-bundle\Registry.php on line 41
!!
!!

Installation failed, reverting ./composer.json to its original content.
```

Here is my composer.json file

```json
{
    "type": "project",
    "license": "proprietary",
    "minimum-stability": "beta",
    "require": {
        "php": "^7.0.8",
        "sensio/framework-extra-bundle": "^5.0",
        "symfony/console": "^4.0",
        "symfony/flex": "^1.0",
        "symfony/framework-bundle": "^4.0",
        "symfony/lts": "^4@dev",
        "symfony/twig-bundle": "^4.0@beta",
        "symfony/web-profiler-bundle": "^4.0@beta",
        "symfony/webpack-encore-pack": "^1.0",
        "symfony/yaml": "^4.0"
    },
    "require-dev": {
        "symfony/dotenv": "^4.0",
        "symfony/web-server-bundle": "^4@dev"
    },
    "config": {
        "preferred-install": {
            "*": "dist"
        },
        "sort-packages": true
    },
    "autoload": {
        "psr-4": {
            "App\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "App\\Tests\\": "tests/"
        }
    },
    "scripts": {
        "auto-scripts": {
            "cache:clear": "symfony-cmd",
            "assets:install --symlink --relative %PUBLIC_DIR%": "symfony-cmd"
        },
        "post-install-cmd": [
            "@auto-scripts"
        ],
        "post-update-cmd": [
            "@auto-scripts"
        ]
    },
    "conflict": {
        "symfony/symfony": "*"
    },
    "extra": {
        "symfony": {
            "id": "01BWYDEM7TY26M6PSQCVJE2DN3",
            "allow-contrib": false
        }
    }
}

```

Perhaps we could make a stable release work with symfony 4 in addition to this issue?

**Comment by Majkl578** [comment]
This is not a bug in ORM itself, please report it to [DoctrineBundle](https://github.com/doctrine/DoctrineBundle) (or Flex recipes if this is a recipe bug).
