### ISSUE TITLE
doctrine orm Identity through foreign Entities Bug (when identifiers are of type RamseyUuid)

### ISSUE THREAD

**Issue by pytoccaz** [doctrine/doctrine2#9335]
Hello doctrine community, 

### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | maybe ?
| Version     | 2.10.4

#### Summary

On a symfony api-platform project we tried to upgrade the following components :
symfony 5.2 --> symfony 5.4
php7.4 --> php8.1
mysql internal guid --> doctrine generated Ramsey uuid

All our entities verifying [Identity through foreign Entities](https://www.doctrine-project.org/projects/doctrine-orm/en/2.10/tutorials/composite-primary-keys.html#identity-through-foreign-entities) design pattern lead to a break in code when "foreign entities" are refreshed.

#### Current buggy behavior

A buggy case with those 2 entities:

```php 
// Book.php
/**
 * @ORM\Entity 
 * @ORM\Table(name="book")
 */
class Book
{
    /**
     * @var \Ramsey\Uuid\UuidInterface
     *
     * @ORM\Id
     * @ORM\Column(type="uuid", unique=true)
     * @ORM\GeneratedValue(strategy="CUSTOM")
     * @ORM\CustomIdGenerator(class=UuidGenerator::class)
     */
    protected $id;
```

```php
// Author.php
/**
 * @ORM\Entity 
 * @ORM\Table(name="author")
 */
class Author
{  
 
    /**
     * @ORM\Id
     * @ORM\OneToOne(targetEntity="Book", inversedBy="author")
     * @ORM\JoinColumn(name="book")  
     */
    protected $book;

```

1. `Book` is identified by `$id` of type *Ramsey Uuid*
2.  `Author` is identified by `$book` of type `Book` (hence Book is the foreign entity). 

Note `@ORM\JoinColumn(name="book")` in `Author` class.
When `Author` `book` identifier is mapped with the same named `book` table column, doctrine hydrator breaks with the following error message when refreshing `Book` enties:

```
PHP Fatal error:  Uncaught ReflectionException: Given object is not an instance of the class this property was declared in in /home/olivier/work/projet/tests/doctrine/doctrine2-tutorial/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php:791
Stack trace:
#0 /home/olivier/work/projet/tests/doctrine/doctrine2-tutorial/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php(791): ReflectionProperty->getValue()
#1 /home/olivier/work/projet/tests/doctrine/doctrine2-tutorial/vendor/doctrine/orm/lib/Doctrine/ORM/Utility/IdentifierFlattener.php(66): Doctrine\ORM\Mapping\ClassMetadataInfo->getIdentifierValues()
#2 /home/olivier/work/projet/tests/doctrine/doctrine2-tutorial/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(2654): Doctrine\ORM\Utility\IdentifierFlattener->flattenIdentifier()
#3 /home/olivier/work/projet/tests/doctrine/doctrine2-tutorial/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/ObjectHydrator.php(255): Doctrine\ORM\UnitOfWork->createEntity()
#4 /home/olivier/work/projet/tests/doctrine/doctrine2-tutorial/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/ObjectHydrator.php(422): Doctrine\ORM\Internal\Hydration\ObjectHydrator->getEntity()
#5 /home/olivier/work/projet/tests/doctrine/doctrine2-tutorial/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/ObjectHydrator.php(143): Doctrine\ORM\Internal\Hydration\ObjectHydrator->hydrateRowData()
#6 /home/olivier/work/projet/tests/doctrine/doctrine2-tutorial/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/AbstractHydrator.php(268): Doctrine\ORM\Internal\Hydration\ObjectHydrator->hydrateAllData()
#7 /home/olivier/work/projet/tests/doctrine/doctrine2-tutorial/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(808): Doctrine\ORM\Internal\Hydration\AbstractHydrator->hydrateAll()
#8 /home/olivier/work/projet/tests/doctrine/doctrine2-tutorial/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(2207): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->refresh()
#9 /home/olivier/work/projet/tests/doctrine/doctrine2-tutorial/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(2179): Doctrine\ORM\UnitOfWork->doRefresh()
#10 /home/olivier/work/projet/tests/doctrine/doctrine2-tutorial/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(687): Doctrine\ORM\UnitOfWork->refresh()
#11 /home/olivier/work/projet/tests/doctrine/doctrine2-tutorial/create_book.php(23): Doctrine\ORM\EntityManager->refresh()
#12 {main}
  thrown in /home/olivier/work/projet/tests/doctrine/doctrine2-tutorial/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php on line 791
```

If you change JoinColumn name attribute with a name != "book" then it works fine. 

If you use an auto-incremented interger Ids it works as it always did. 

#### How to reproduce

Please go to https://github.com/pytoccaz/doctrine-ramseyuuid-bug

#### Expected behavior
that code doesn't break :
```php 
$entityManager->refresh($book);
```

**Comment by pytoccaz** [comment]
I tested with symfony Uuid and Ulid types and did not reproduced the bug. 
@see https://github.com/pytoccaz/doctrine-ramseyuuid-bug/tree/test-symfony-ulid
@see https://github.com/pytoccaz/doctrine-ramseyuuid-bug/tree/test-symfony-uuid

The use of Ramsey uuids seems to be the root cause.

**Comment by pytoccaz** [comment]
Same issue with symfony UUID or symfony ULID

@see https://github.com/pytoccaz/doctrine-ramseyuuid-bug/tree/test-symfony-ulid
@see https://github.com/pytoccaz/doctrine-ramseyuuid-bug/tree/test-symfony-uuid
